### ISSUE TITLE
FANIoT Image sizes and labels

### ISSUE THREAD

**Issue by mtaha1996** [Avidnet/Avidnet.github.io#22]
with do respect to you, there is something that we should pay attention:
![screenshot from 2019-01-03 14-57-56](https://user-images.githubusercontent.com/11257033/50635661-55158580-0f68-11e9-87f7-822a913e7bd8.png)
![screenshot from 2019-01-03 14-58-03](https://user-images.githubusercontent.com/11257033/50635662-55ae1c00-0f68-11e9-800b-b6c627d568ea.png)

**Comment by 1995parham** [comment]
@mtaha1996 Thanks for your attention. I will check it.

**Comment by 1995parham** [comment]
I think the issue with section background has been corrected.
